### ISSUE TITLE
Redefinition of 'RCTMethodInfo' in 'rn55'

### ISSUE THREAD

**Issue by ysfox** [lovebing/react-native-baidu-map#179]
Redefinition of 'RCTMethodInfo'  in 'RN55' 

![00d3bbb3-abef-4616-bb68-c1d000a15441](https://user-images.githubusercontent.com/3353331/41146595-6b8d1214-6b36-11e8-8dea-d097459bc948.png)

**Comment by suijunqiang** [comment]
same error on rn 0.56, and the workaround is that replease all  #import "RCTBridgeModule.h"  in the project,  but still have other errors.
#if __has_include(<React/RCTBridgeModule.h>)
  #import <React/RCTBridgeModule.h>
#else
  #import "RCTBridgeModule.h"
#endif

**Comment by suijunqiang** [comment]
https://github.com/yonahforst/react-native-permissions/issues/137

**Comment by suijunqiang** [comment]
I have verified it works well on the "react-native": "^0.46.0"
